PipelineSecrets:
  DockerConfig: '{"auths":{"servantkiwi.azurecr.io":{"auth":"c2VydmFudGtpd2k6SG9tU3lrTDVJWDRxVXhCTEhzdGtkUStzYzR5V3BoeEY="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild:
  enabled: null
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: ampel-tacho.de
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: servantkiwi.azurecr.io
        TILLER_NAMESPACE: kube-system
  enabled: null
prow: {}
